# https://developer.sabre.com/docs/read/rest_apis/
---
swagger: '2.0'
info:
  title: Geo Search
  version: v2
  description: The Geo Search API identifies airports, hotels, and car rental locations that fall within a given geographic search location using a radius search.
  contact:
    name: Contact Us
    url: 'https://developer.sabre.com/support'
x-project-id: geosearchv2
host: api-crt.cert.havail.sabre.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v2/geo/search:
    post:
      operationId: geoSearch
      parameters:
        - name: geoSearchRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/GeoSearchRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/GeoSearchResponse'
          description: Success
        '400':
          description: |
            Bad Request

            - The request was not valid.
        '404':
          description: |
            Not Found

            - No results were found.
definitions:
  GeoSearchRequest:
    description: Contains the required parameters to request airports/hotels/car rental locations within a specified radius.
    type: object
    properties:
      GeoSearchRQ:
        type: object
        description:  Contains the required parameters to request airports/hotels/car rental locations within a specified radius.
        required:
          - GeoRef
          - GeoAttributes
        properties:
          GeoRef:
            type: object
            description: Contains the required parameters to search by.
            properties:
              Category: 
                type: string
                example: HOTEL
                description: The specification of whether an airport, hotel or car rental location should be returned.
                enum: 
                  - HOTEL
                  - CAR
                  - AIR
              Radius:
                type: number
                example: 1
                description: Specifies the maximum distance of a location from the given reference point.
              Direction:
                type: string
                example: N
                description: The direction from which the search begins.
                enum: 
                  - N
                  - S
                  - E
                  - W
                  - NE
                  - NW
                  - SE
                  - SW
              UOM:
                type: string
                description: The unit of measure (UOM) to be used for the search radius distance. Can be `MI` for mile or `KM` for kilometer.
                example: KM
                enum: 
                  - MI
                  - KM
              GeoCode:
                type: object
                description: Contains latitude and longitude information used to request hotels within a specific geographical location.
                required:
                  - Latitude
                  - Longitude
                properties:
                    Latitude:
                        type: number
                        example: 32.877416
                        description: The latitude from which to search by.
                    Longitude:
                        type: number
                        example: -96.959879
                        description: The longitude from which to search by.
              AirportCode:
                type: string
                pattern: '[A-Z0-9]{3}'
                example: 'DFW'
                description: The IATA-standard three-letter airport code.
              Address:
                type: string
                minLength: 0
                maxLength: 50
                description: The exact location of the airport. The characters to specify the address can range from 0 to 50.
                example: Hidden Ridge Street Irving City
              POI:
                type: string
                minLength: 0
                maxLength: 20
                description: The point of interest to search by. Points of interest refer to a specific location that someone may find useful or interesting, like a monument or noteworthy building.
                example: Eiffel Tower
              HotelCode:
                type: string
                pattern: '[0-9]{1,}'
                example: '100066952'
                description: The unique property number of the hotel.
              RefPoint:
                type: object
                description: Contains required parameters to request locations by name, state name, or country code.
                required: 
                  - Value
                  - ValueContext
                  - RefPointType
                properties: 
                  Value: 
                    type: string
                    minLength: 3
                    maxLength: 50
                    example: park
                    description: The open-ended text-based reference point from which the search begins.
                  ValueContext:
                    type: string
                    enum: 
                      - NAME
                      - CODE
                    example: NAME
                    description: The type of information entered into Value. Can be NAME when the name of a location has been entered, or CODE if there a specific code associated with the location.
                  RefPointType:
                    type: string
                    example: '6'
                    description: The Online Travel Agency (OTA) code, corresponding to the location type entered into Value. Can be 5 CITY, 6 AIRPORT, 7 RAIL STATION, 11 HOTEL, 16 ATTRACTION, 18 CAR RENTAL LOCATION.
                    enum: 
                      - 6
                      - 7
                      - 11
                      - 16
                      - 18
                      - 37
                  StateProv:
                    type: string
                    description: The name of the state or province where the address is located.
                    minLength: 2
                    maxLength: 50
                    example: TX
                  CountryCode:
                    type: string
                    minLength: 2
                    maxLength: 50
                    example: US
                    description: The unique code of the country where the address is located.
                  PostalCode:
                    type: string
                    minLength: 2
                    maxLength: 50
                    example: '75038'
                    description: The postal code of the address. Differs in required length depending on country of origin.
                  CityName:
                    type: string
                    minLength: 2
                    maxLength: 50
                    example: Irvine
                    description: The name of the city where the reference point is located.
              AddressRef:
                type: object
                description: Contains the required parameters to request hotels in a specific address area within the requested radius.
                required:
                  - CountryCode
                properties:
                  Street:
                    type: string
                    minLength: 0
                    maxLength: 50
                    example: Hidden Ridge
                    description: The name of the street where the address is located.
                  City:
                    type: string
                    minLength: 0
                    maxLength: 50
                    description: The name of the city where the address is located.
                    example: irvine
                  County:
                    type: string
                    minLength: 0
                    maxLength: 50
                    example: Dallas
                    description: The name of the country where the address is located.
                  PostalCode:
                    type: string
                    minLength: 0
                    maxLength: 50
                    example: '75038'
                    description: The postal code of the address. It can range from 0 to 50 characters.
                  StateProv:
                    type: string
                    minLength: 0
                    maxLength: 50
                    example: TX
                    description: The name of the state or province where the address is located.
                  CountryCode:
                    type: string
                    minLength: 0
                    maxLength: 50
                    example: US
                    description: The unique code of the country where the address is located.
          GeoAttributes:
            type: object
            description: Contains geographic properties to filter by.
            properties:
              Attributes:
                type: array
                minItems: 0
                maxItems: 10
                description: Lists properties to filter by, like `Name` and `Value`.
                items:
                  type: object
                  required: 
                    - Name
                    - Value
                  properties:
                    Name:
                      type: string
                      example: CHAIN
                      description: The name of the Geo attribute.
                    Value:
                      type: string
                      example: HC
                      description: The value of the Geo attribute.
  GeoSearchResponse:
    type: object
    description: Contains the GeoServices response parameters to the requested search criteria.
    properties:
      GeoSearchRS:
        type: object
        description: Contains the result parameters found within the requested search radius.
        properties: 
          ApplicationResults:
            type: object
            description: Contains the result references specifically as the contents of a Sabre SOAP Fault/detail element.
            properties:
              Success:
                type: array
                items:
                  type: object
                  properties:
                    TimeStamp:
                      type: string
                      example: '2016-10-03T03:35:09.473-05:00'
                      description: The time stamp record as to when the data was retrieved.
          GeoSearchResults: 
            type: object
            description: Contains the results found within the specified radius.
            properties:
              Radius:
                type: number
                example: 1
                description: The radius in which the geographic search occurred.
              UOM:
                type: string
                example: KM
                description: The unit of measurement used for the `Radius`.
                enum:
                  - MI
                  - KM
              Category:
                type: string
                example: HOTEL
                description: The specification of the line of business which can be hotel/car/air.
                enum: 
                  - HOTEL
                  - CAR
                  - AIR
              Latitude:
                type: number
                example: 32.877416
                description: The geographic latitude of the location.
              Longitude:
                type: number
                example: -96.959879
                description: The geographic longitude of the location.
              MaxSearchResults:
                type: number
                example: 18
                description: The maximum allowable number of results in the response.
              OffSet: 
                type: number
                example: 1
                description: The distance from which a result has deviated from the initial search radius.
              GeoSearchResult:
                type: array
                description: Lists the results found within the specified radius.
                minItems: 1
                maxItems: 50
                items:
                  type: object
                  description: Contains all results found within the specified radius.
                  properties: 
                    Distance:
                      type: number
                      example: 0.24
                      description: Specifies distance of the hotel from the given airport.
                    Direction:
                      type: string
                      example: N
                      description: The direction of the specified location.
                    Latitude:
                      type: number
                      example: 32.880778
                      description: The geographic latitude of the location.
                    Longitude:
                      type: number
                      example: -96.961008
                      description: The geographic longitude of the location.
                    Name: 
                      type: string
                      example: 'MARRIOTT EXECUSTAY BEAVER CREEK'
                      description: The name of the location.
                    Id: 
                      type: string
                      example: '86034'
                      description: The unique ID of the location.
                    Street: 
                      type: string
                      example: 1000 Meadow Creek Drive
                      description: The street address.
                    Zip: 
                      type: string
                      example: '75038'
                      description: The zip code of the location.
                    City: 
                      type: string
                      example: Irvine
                      description: The name of the city.
                    State: 
                      type: string
                      example: TX
                      description: The two-letter state code.
                    Country: 
                      type: string
                      example: US
                      minimum: 2
                      maxLength: 50
                      description: The code of the country. The length of the code ranges from 2 to 50.
                    ConfidenceFactor: 
                      type: integer
                      description: ConfidenceFactor types
                      example: 1
                    Attributes:
                      type: object
                      description: Contains property filters, like `Name` and `Value`.
                      properties:
                        Attribute:
                          type: array
                          description: Lists property filters, like `Name` and `Value`.
                          minItems: 0
                          maxItems: 10
                          items:
                            type: object
                            properties:
                              Name:
                                type: string
                                example: LOCALAREA
                                description: The specification when the property was filtered by name. Can only be 'LOCALAREA'.
                              Id:
                                type: string
                                example: '900011743'
                                description: The unique ID of the `attribute`.
                              Value:
                                type: string
                                example: Carrier
                                description: The specification when the response includes only locations inside a specified area when 'LOCALAREA' is present in 'Name'.
                                

securityDefinitions:
  oauth2_authentication:
    type: oauth2
    tokenUrl: 'https://api-crt.cert.havail.sabre.com/v2/auth/token'
    flow: application
    x-base64-encode-client-credentials: true
security:
  - oauth2_authentication: []