openapi: 3.0.0
info:
  title: Carbon Intensity API
  description: |-
    National Grid's Carbon Intensity API provides an indicative trend of regional carbon intensity of the electricity system in Great Britain (GB) up to 2 days ahead of real-time. It provides programmatic and timely access to both forecast and estimated carbon intensity data. The Carbon Intensity forecast includes CO2 emissions related to electricity generation only. The includes emissions from all large metered power stations, interconnector imports, transmission and distribution losses, and accounts for national electricity demand, embedded wind and solar generation.
  contact:
    name: National Grid
    email: alasdair.bruce@nationalgrid.com
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  version: 2.0.0
externalDocs:
  description: Find out more about Carbon Intensity API
  url: https://carbonintensity.org.uk/
servers:
  - url: https://api.carbonintensity.org.uk
tags:
  - name: intensity
    description: Carbon Intensity - National
  - name: stats
    description: Statistics - National
paths:
  /intensity:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data for current half hour.
      description: Retrieves Carbon Intensity data for the current half hour. All times provided in UTC (+00:00).
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/date:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data for today.
      description: Get Carbon Intensity data for today. All times provided in UTC (+00:00).
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Intensity"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /intensity/date/{date}:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data for a specific date.
      description: Get Carbon Intensity data for a specific date. All times provided in UTC (+00:00).
      parameters:
        - name: date
          in: path
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            example: 2023-01-25
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        '400':
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/date/{date}/{period}:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data for specific date and period.
      description: Get Carbon Intensity data for a specific date and half hour settlement period. All times provided in UTC (+00:00).
      parameters:
        - name: date
          in: path
          required: true
          description: Date in YYYY-MM-DD format.
          schema:
            type: string
            example: 2023-01-25
        - name: period
          in: path
          required: true
          description: Half hour settlement period between 1-48.
          schema:
            type: string
            example: 42
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/factors:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity factors for each fuel type.
      description: Get Carbon Intensity factors for each fuel type.
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data for specific half hour period.
      description: Returns carbon intensity data for a specific half hour period. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          description: Datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/fw24h:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data 24hrs forwards from specific datetime.
      description: Get Carbon Intensity data between the {from} datetime specified and 24hrs before. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          description: Start datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/fw48h:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data 48hrs forwards from specific datetime.
      description: Get Carbon Intensity data between the {from} datetime specified and 48hrs after. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          description: Start datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/pt24h:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data 24hrs in the past of a specific datetime.
      description: Get Carbon Intensity data between the {from} datetime specified and 24hrs before. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          description: Start datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/{from}/{to}:
    get:
      tags:
        - intensity
      summary: Get Carbon Intensity data between from and to datetime
      description: Get Carbon Intensity data between the {from} and {to} datetimes. The maximum date range is limited to 14 days. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          description: Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ
          required: true
          schema:
            type: string
            example: 2023-01-25T12:35Z
        - name: to
          in: path
          description: End datetime in in ISO8601 format YYYY-MM-DDThh:mmZ
          required: true
          schema:
            type: string
            example: 2023-01-26T12:35Z
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intensity'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/stats/{from}/{to}:
    get:
      tags:
        - stats
      summary: Get Carbon Intensity statistics
      description: Get Carbon Intensity statistics (average, max, mean) between from and to datetime. The maximum date range is limited to 30 days. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          description: Start datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          schema:
            type: string
            example: 2023-01-25T12:35Z
        - name: to
          in: path
          required: true
          description: End datetime in ISO8601 format YYYY-MM-DDThh:mmZ.
          schema:
            type: string
            example: 2023-01-26T12:35Z
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /intensity/stats/{from}/{to}/{block}:
    get:
      tags:
        - stats
      summary: Get block average Carbon Intensity statistics
      description: Get block average Carbon Intensity statistics (average, max, mean) between from and to datetime. The maximum date range is limited to 30 days. The block length must be between 1 and 24 hours and should be an integer. All times provided in UTC (+00:00).
      parameters:
        - name: from
          in: path
          required: true
          description: Start datetime in in ISO8601 format YYYY-MM-DDThh:mmZ
          schema:
            type: string
            example: 2023-01-25T12:35Z
        - name: to
          in: path
          required: true
          description: End datetime in in ISO8601 format YYYY-MM-DDThh:mmZ
          schema:
            type: string
            example: 2023-01-26T12:35Z
        - name: block
          in: path
          required: true
          description: Block length in hours i.e. a block length of 2 hrs over a 24 hr period returns 12 items with the average, max, min for each 2 hr block e.g. 2017-08-26T17:00Z/2017-08-27T17:00Z/2
          schema:
            type: string
            example: 2017-08-26T17:00Z/2017-08-27T17:00Z/2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Intensity:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
                format: date-time
              to:
                type: string
                format: date-time
              intensity:
                type: object
                properties:
                  forecast:
                    type: number
                  actual:
                    type: number
                  index:
                    type: string
    Factors:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              Biomass:
                type: number
              Coal:
                type: number
              Dutch Imports:
                type: number
              French Imports:
                type: number
              Gas (Combined Cycle):
                type: number
              Gas (Open Cycle):
                type: number
              Hydro:
                type: number
              Irish Imports:
                type: number
              Nuclear:
                type: number
              Oil:
                type: number
              Other:
                type: number
              Pumped Storage:
                type: number
              Solar:
                type: number
              Wind:
                type: number
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
    Statistics:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
                format: date-time
              to:
                type: string
                format: date-time
              intensity:
                type: object
                properties:
                  max:
                    type: number
                  average:
                    type: number
                  min:
                    type: number
                  index:
                    type: string
