openapi: 3.0.0
servers:
  - description: CalorieNinjas API server
    url: api.calorieninjas.com
info:
  contact:
    email: info@calorieninjas.com
    name: CalorieNinjas team
    url: calorieninjas.com
  description: Natural language nutrition API to extract nutrition data from any text.
  license:
    name: Apache 2.0
    url: http://apache.org/licenses/LICENSE-2.0.html
  termsOfService: calorieninjas.com/tos
  title: CalorieNinjas
  version: 1.0.0
  x-apisguru-categories:
    - text
  x-origin:
    - format: openapi
      url: https://calorieninjas.com/openapi.json
      version: "3.0"
  x-providerName: calorieninjas.com
externalDocs:
  description: See calorieninjas.com/api.
  url: calorieninjas.com/api
security:
  - x-api-key: []
tags: []
paths:
  /v1/nutrition:
    get:
      description: "Returns a list of food item nutrition facts extracted from an input string containing food and beverage words. "
      externalDocs:
        url: calorieninjas.com/api
      operationId: ""
      parameters:
        - description: Input query containing food and/or beverage words.
          in: query
          name: query
          required: true
          schema:
            maxLength: 1500
            minLength: 0
            type: string
      responses:
        default:
          description: Default response
      summary: Get nutrition text for an input string containing food and beverage words.
components:
  callbacks: {}
  links: {}
  requestBodies: {}
  schemas: {}
  securitySchemes:
    x-api-key:
      in: header
      name: api_key
      type: apiKey
